spring.application.name=backend

# Conexión MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_backend?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Cloudinary
cloudinary.cloud_name=dydfkayre
cloudinary.api_key=835384435632141
cloudinary.api_secret=GBdEAU_2SxJ8VSN1qxr-LDAWVaE



